# Generated by Django 4.0 on 2022-08-05 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='sub_tasks',
            new_name='sub_task',
        ),
    ]
